version: "3.9"
services:
  agent:
    image: aron666/titan-agent:test
    environment:
      - KEY=WEXRVMW8zXCL
    privileged: true
    cap_add:
      - ALL
    devices:
      - /dev/kvm:/dev/kvm
    # network_mode: "host"
    restart: always
    volumes:
      - ./data:/app/data
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: amd64